### ISSUE TITLE
FeedBack Front

### ISSUE THREAD

**Issue by szuluaga-beep** [codigoc13/c13-app-back#28]
¿ Al momento de crear un usuario se le va a poder enviar una imagen, algo que sea como un tipo de avatar o parecido?
  - Si se puede hacer, no muetra la forma en la que se envía la imagen, no se sabe si solo es una url o debemos enviar como si fuera un string

1- Agregar en la documentación si se necesita token para actualizar el usuario
2- Agregar en la documentación como se puede agregar una imagen para crear la noticia
3- La hora de la creación de la noticia no es la de Colombia
4-¿ Al momento de crear un articulo se le va a poder enviar una imagen la cual sea referente a la noticia que va dirijida?
4.1 - La hora de la creación del artículo no es la de Colombia
![image](https://user-images.githubusercontent.com/69664305/204057515-2041a70a-33f0-4786-843a-df541facc96e.png)

5- Agregar en la documentación como se puede agregar una imagen para crear el curso
6- La hora de la creación del curso no es la de Colombia
![image](https://user-images.githubusercontent.com/69664305/204057538-3b830664-e4fb-41e7-bae6-5f9f689b6a27.png)

7- Se puede agregar una imagen a la cohorte??
8- La hora de la creación de la cohorte no es la de Colombia

![image](https://user-images.githubusercontent.com/69664305/204057543-bdfc4c5d-c0cc-4afd-ab86-aa6c1f685339.png)

9- Se puede agregar una imagen a la carrera??
10- La hora de la creación de la carrera no es la de Colombia
![image](https://user-images.githubusercontent.com/69664305/204057553-6937c511-36f8-46c3-a571-7a12e3b0985f.png)

**Comment by seraleman** [comment]
En este mensaje se dará respuesta a las preguntas que la tengan de manera inmediata. Para las demás y de ser necesario se abrirán issues independientes. 

- [x] Se abre issue #29 para la implementación de guardar imagen para todos los modelos-entidades en su creación y edición.
- [x] 1. Se abre issue #30
- [x] 2. Va en issue #29
- [x] 3. Se abre issue #31
- [x] 4. Va en issue #29
- [x] 4.1. Se abre issue #32 
- [x] 5. Va en issue #29
- [x] 6. Se abre issue #33
- [x] 7. Va en issue #29
- [x] 8. Se abre issue #34
- [x] 9. Va en issue #29
- [x] 10. Se abre issue #35

**Comment by seraleman** [comment]
Se realizan los cambios recomendados en la retroalimentación del front.
